encoding: utf-8

# SEOç›¸å…³ä¿¡æ¯
title: ç™½æ—¥æ¢¦æƒ³å®¶
description: DXHçš„ä¸ªäººåšå®¢
keywords: DXH,Blog,ç™½æ—¥æ¢¦,ç™½æ—¥æ¢¦æƒ³å®¶
author: DXH
footerText: 'Copyright Â© 2019 Daythink.Net ğŸ§¡ All Rights Reserved.'

# åŸŸåé…ç½®,ç”Ÿæˆsitemapä¼šç”¨åˆ°ï¼Œå‹é“¾ä¹Ÿä¼šç”¨åˆ°
domainUrl: 'https://daythink.net'
# è·¯å¾„é…ç½®ï¼Œé™æ€èµ„æº404ä¸€èˆ¬æ˜¯è¿™é‡Œä¸å¯¹
# ç›´æ¥åŸŸåè®¿é—®è®¾ç½®ä¸º'',æœ‰å¦‚æœæ˜¯user.github.io/blog/è®¿é—®çš„è¯è®¾ç½®ä¸º'/blog'
baseUrl: ''

# èœå•
menu:
  - title: é¦–é¡µ
    url: /
  - title: åˆ†ç±»
    url: /pages/åˆ†ç±».html
  - title: é˜…è¯»
    url: /pages/é˜…è¯».html
  - title: åˆ©å™¨
    url: /pages/åˆ©å™¨.html
  - title: ç•™è¨€
    url: /pages/ç•™è¨€.html
  - title: å…³äº
    url: /pages/å…³äº.html
  - title: æœç´¢
    url: /pages/æœç´¢.html

# æ–‡ç« urlå‰ç¼€ï¼Œå›ºå®šæ ¼å¼ï¼Œä¸è¦åŠ¨
permalink: /posts/:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  input: GFM

exclude: ['CNAME', 'README.md', 'build-tool']
